version: '3'

services:
 db:
  image: mysql/mysql-server
  container_name: db
  restart: always
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: 123456
 #  MYSQL_USER: jun
 #  MYSQL_PASSWORD: 123456
  volumes:
   - ./mysql-init:/docker-entrypoint-initdb.d
 web:
   build: .
   container_name: aspnetcore
   ports:
    - "8090:5000"
   depends_on:
    - db